name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: make V=1
      
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: test unit
      run: make test_unit V=1
      
    - name: test functional
      run: make test_functional V=1
      
    - name: test cpp
      run: make test_cpp V=1
      

