name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os:         [ubuntu-latest]
        cc:         [gcc]
        make_flags: ["CFLAGS='-Werror'", "NO_VALGRIND=1 USE_STANDARD_TMPFILE=1 CFLAGS='-Werror'"]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: ${{ matrix.make_flags }} make V=1
      
#    - name: Install test dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pytest

    #- name: Install package
    #  run: |
    #    sudo apt-get -y install valgrind
    
#    - name: test unit
#      run: make test_unit V=1
      
#    - name: test functional
#      run: make test_functional V=1
      
#    - name: test cpp
#      run: make test_cpp V=1
      
#    - name: test valgrind
#      run: make test_valgrind V=1
 
#    - name: test cmake
#      run: |
#        pwd
#        ls -l
#        make test_cmake V=1

