name: Build with CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        sudo apt-get -y install libminizip-dev
        sudo apt-get -y install libssl-dev
        sudo apt-get -y install valgrind
        sudo apt-get -y install zlib1g-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/cmake
      run:  cmake .. -DBUILD_TESTS=ON

    - name: Build
      working-directory: ${{github.workspace}}/cmake
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/cmake
      run: ./xlsxwriter_unit
