name: Cmake on Windows

on: [push, pull_request]

jobs:
  build:
    name: CMake on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        vcpkg.exe install zlib:x64-windows
        vcpkg.exe integrate install

    - name: Configure CMake
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        cd cmake
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        cd cmake
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --build . --config Release
