name: Cmake on Windows

on: [push]



jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo "-----------------------------"
        dir
        mkdir build
        cd build
        echo "-----------------------------"
        vcpkg.exe --version
        vcpkg.exe install zlib
        vcpkg.exe integrate install
        echo "-----------------------------"
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        echo "-----------------------------"
        cmake --build . --config Release
        
      
